# Generated by Django 4.1.4 on 2023-01-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.FileField(blank=True, default='media/Test results.pdf', null=True, upload_to='uploads/'),
        ),
    ]
